version: "3.8"

services:

  keycloak_db:
    image: postgres
    restart: always
    volumes:
      - keycloak-vol:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - auth-network
  
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    hostname: keycloak
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak_db
      - KC_DB_URL_DATABASE=keycloak_db
      - KC_DB_URL_PORT=5432
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_SCHEMA=public
      - KC_DB_PASSWORD=keycloak_password
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=auth.localhost
      - KC_PROXY=passthrough
      - KC_HTTP_PORT=80
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    networks:
      - auth-network
      - traefik-public
    depends_on: 
      - keycloak_db    
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.keycloak.rule=Host(`${AUTH_DOMAIN?Variable AUTH_DOMAIN not set}`)"
        - "traefik.http.routers.keycloak.entrypoints=http"
        - "traefik.http.routers.keycloak.middlewares=https-redirect"
        - "traefik.http.routers.keycloak-https.rule=Host(`${AUTH_DOMAIN?Variable AUTH_DOMAIN not set}`)"
        - "traefik.http.routers.keycloak-https.entrypoints=https"
        - "traefik.http.routers.keycloak-https.tls.certresolver=le"
        - "traefik.http.services.keycloak.loadbalancer.server.port=80"
    command: start

  forwardauth:
    image: mesosphere/traefik-forward-auth:3.1.0
    networks:
      - traefik-public
    environment:
      - SECRET=${FA_SECRET}
      - PROVIDER_URI=${FA_PROVIDER_URI}
      - CLIENT_ID=${FA_CLIENT_ID}
      - CLIENT_SECRET=${FA_CLIENT_SECRET}
    labels:
      - traefik.enabled=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.forwardauth.loadbalancer.server.port=4181
      - traefik.http.routers.forwardauth.entrypoints=https
      - traefik.http.routers.forwardauth.rule=Path(`/_oauth`)
      - traefik.http.routers.forwardauth.middlewares=traefik-forward-auth
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://forwardauth:4181
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true

volumes:
  keycloak-vol:

networks:
  traefik-public:
    external: true
  auth-network: